const CashOut = [{
    "id": "1001",
    "cash_show": "0.3",
    "cash": "0.3",
    "condition_one": "[1,2]",
    "condition_two": "[]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "1",
    "sdk_rp_id": "3",
    "channel": "[NATIVE,GS]"
  },
  {
    "id": "1002",
    "cash_show": "0.5",
    "cash": "0.5",
    "condition_one": "[2,1001]",
    "condition_two": "[1,5]",
    "condition_three": "[3,2]",
    "integral": "0",
    "is_one_item": "1",
    "sdk_rp_id": "4",
    "channel": "[NATIVE,GS]"
  },
  {
    "id": "2001",
    "cash_show": "15",
    "cash": "15",
    "condition_one": "[1,15]",
    "condition_two": "[3,10]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "1",
    "sdk_rp_id": "5",
    "channel": "[NATIVE,GS]"
  },
  {
    "id": "2002",
    "cash_show": "30",
    "cash": "30",
    "condition_one": "[2,2001]",
    "condition_two": "[1,15]",
    "condition_three": "[3,20]",
    "integral": "0",
    "is_one_item": "2",
    "sdk_rp_id": "6",
    "channel": "[NATIVE,GS]"
  },
  {
    "id": "2003",
    "cash_show": "80",
    "cash": "80",
    "condition_one": "[2,2002]",
    "condition_two": "[4,1]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "0",
    "sdk_rp_id": "7",
    "channel": "[NATIVE,GS]"
  },
  {
    "id": "2004",
    "cash_show": "100",
    "cash": "100",
    "condition_one": "[2,2003]",
    "condition_two": "[4,1]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "0",
    "sdk_rp_id": "8",
    "channel": "[NATIVE,GS]"
  },
  {
    "id": "2005",
    "cash_show": "200",
    "cash": "200",
    "condition_one": "[2,2004]",
    "condition_two": "[4,1]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "0",
    "sdk_rp_id": "9",
    "channel": "[NATIVE,GS]"
  },
  {
    "id": "2006",
    "cash_show": "300",
    "cash": "300",
    "condition_one": "[2,2005]",
    "condition_two": "[4,1]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "0",
    "sdk_rp_id": "10",
    "channel": "[NATIVE,GS]"
  },
  {
    "id": "2007",
    "cash_show": "500",
    "cash": "500",
    "condition_one": "[2,2006]",
    "condition_two": "[4,1]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "0",
    "sdk_rp_id": "11",
    "channel": "[NATIVE,GS]"
  },
  {
    "id": "4001",
    "cash_show": "0.03",
    "cash": "0.03",
    "condition_one": "[1,2]",
    "condition_two": "[]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "1",
    "sdk_rp_id": "61",
    "channel": "[QQ]"
  },
  {
    "id": "4002",
    "cash_show": "0.05",
    "cash": "0.05",
    "condition_one": "[2,1001]",
    "condition_two": "[1,5]",
    "condition_three": "[3,2]",
    "integral": "0",
    "is_one_item": "1",
    "sdk_rp_id": "62",
    "channel": "[QQ]"
  },
  {
    "id": "5001",
    "cash_show": "15",
    "cash": "15",
    "condition_one": "[1,15]",
    "condition_two": "[3,10]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "1",
    "sdk_rp_id": "63",
    "channel": "[QQ]"
  },
  {
    "id": "5002",
    "cash_show": "30",
    "cash": "30",
    "condition_one": "[2,2001]",
    "condition_two": "[1,15]",
    "condition_three": "[3,20]",
    "integral": "0",
    "is_one_item": "2",
    "sdk_rp_id": "64",
    "channel": "[QQ]"
  },
  {
    "id": "5003",
    "cash_show": "80",
    "cash": "80",
    "condition_one": "[2,2002]",
    "condition_two": "[4,1]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "0",
    "sdk_rp_id": "65",
    "channel": "[QQ]"
  },
  {
    "id": "5004",
    "cash_show": "100",
    "cash": "100",
    "condition_one": "[2,2003]",
    "condition_two": "[4,1]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "0",
    "sdk_rp_id": "66",
    "channel": "[QQ]"
  },
  {
    "id": "5005",
    "cash_show": "200",
    "cash": "200",
    "condition_one": "[2,2004]",
    "condition_two": "[4,1]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "0",
    "sdk_rp_id": "67",
    "channel": "[QQ]"
  },
  {
    "id": "5006",
    "cash_show": "300",
    "cash": "300",
    "condition_one": "[2,2005]",
    "condition_two": "[4,1]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "0",
    "sdk_rp_id": "68",
    "channel": "[QQ]"
  },
  {
    "id": "5007",
    "cash_show": "500",
    "cash": "500",
    "condition_one": "[2,2006]",
    "condition_two": "[4,1]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "0",
    "sdk_rp_id": "69",
    "channel": "[QQ]"
  },
  {
    "id": "6001",
    "cash_show": "0.3",
    "cash": "0.3",
    "condition_one": "[1,2]",
    "condition_two": "[]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "1",
    "sdk_rp_id": "3",
    "channel": "[WECHAT]"
  },
  {
    "id": "6002",
    "cash_show": "0.5",
    "cash": "0.5",
    "condition_one": "[2,1001]",
    "condition_two": "[1,5]",
    "condition_three": "[3,2]",
    "integral": "0",
    "is_one_item": "1",
    "sdk_rp_id": "4",
    "channel": "[WECHAT]"
  },
  {
    "id": "7001",
    "cash_show": "15",
    "cash": "15",
    "condition_one": "[1,15]",
    "condition_two": "[3,10]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "1",
    "sdk_rp_id": "5",
    "channel": "[WECHAT]"
  },
  {
    "id": "7002",
    "cash_show": "30",
    "cash": "30",
    "condition_one": "[2,2001]",
    "condition_two": "[1,15]",
    "condition_three": "[3,20]",
    "integral": "0",
    "is_one_item": "2",
    "sdk_rp_id": "6",
    "channel": "[WECHAT]"
  },
  {
    "id": "7003",
    "cash_show": "80",
    "cash": "80",
    "condition_one": "[2,2002]",
    "condition_two": "[4,1]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "0",
    "sdk_rp_id": "7",
    "channel": "[WECHAT]"
  },
  {
    "id": "7004",
    "cash_show": "100",
    "cash": "100",
    "condition_one": "[2,2003]",
    "condition_two": "[4,1]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "0",
    "sdk_rp_id": "8",
    "channel": "[WECHAT]"
  },
  {
    "id": "7005",
    "cash_show": "200",
    "cash": "200",
    "condition_one": "[2,2004]",
    "condition_two": "[4,1]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "0",
    "sdk_rp_id": "9",
    "channel": "[WECHAT]"
  },
  {
    "id": "7006",
    "cash_show": "300",
    "cash": "300",
    "condition_one": "[2,2005]",
    "condition_two": "[4,1]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "0",
    "sdk_rp_id": "10",
    "channel": "[WECHAT]"
  },
  {
    "id": "7007",
    "cash_show": "500",
    "cash": "500",
    "condition_one": "[2,2006]",
    "condition_two": "[4,1]",
    "condition_three": "[]",
    "integral": "0",
    "is_one_item": "0",
    "sdk_rp_id": "11",
    "channel": "[WECHAT]"
  }
];
module.exports = CashOut;